# Generated by Django 6.0.1 on 2026-02-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name_plural': 'Berita'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Berita Utama'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
