# Generated by Django 6.0.1 on 2026-02-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_category_news_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narapidana', models.PositiveIntegerField(default=0, verbose_name='Narapidana')),
                ('tahanan', models.PositiveIntegerField(default=0, verbose_name='Tahanan')),
                ('titipan', models.PositiveIntegerField(default=0, verbose_name='Titipan')),
                ('petugas_jaga', models.PositiveIntegerField(default=0, verbose_name='Petugas Jaga')),
                ('program_pembinaan_aktif', models.PositiveIntegerField(default=0, verbose_name='Program Pembinaan Aktif')),
                ('survey_kepuasan', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Survey Kepuasan (%)')),
            ],
            options={
                'verbose_name': 'Statistik Homepage',
                'verbose_name_plural': 'Statistik Homepage',
            },
        ),
    ]
